### ISSUE TITLE
I can not enter 127.0.0.1 with installation by docker

### ISSUE THREAD

**Issue by javiges** [flobz/psacc-ha#15]
docker run -d -ti --name psa_car_controller1 \
  --publish 5000:5000 \
  -v /docker/config:/config \
  --restart unless-stopped \
  flobz/psa_car_controller

I used this to create the docker but when I give the ip http://127.0.0.1:5000, nothing happens

**Comment by flobz** [comment]
Please open an issue on psa_car_controller repo.
