### ISSUE TITLE
Crash after submit car info

### ISSUE THREAD

**Issue by JulienADD** [flobz/psacc-ha#16]
Hi,
Impossible to configure this program, nothing appear after the submit on my car info, the log :
`Containerised psa_car_controller loading...
2021-11-26 14:44:50,065 :: WARNING :: Can't get language
2021-11-26 14:44:56,311 :: INFO :: update_data
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
172.30.32.1 - - [26/Nov/2021 15:25:22] "GET / HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:25:22] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:25:22] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:25:22] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:25:22] "GET /config_login HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:25:22] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:25:22] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:25:23] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:25:23] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [26/Nov/2021 15:25:23] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [26/Nov/2021 15:25:23] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:33:49] "GET / HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:33:50] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:33:50] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:33:50] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:33:50] "GET /assets/images/settings.svg HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:33:50] "GET /config_login HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:33:50] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:33:50] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:33:50] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:33:51] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [26/Nov/2021 15:33:51] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [26/Nov/2021 15:33:51] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:33:54] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:34:08] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:34:08] "GET /config_login HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:34:08] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:34:08] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:34:09] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:34:09] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [26/Nov/2021 15:34:09] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [26/Nov/2021 15:34:09] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:34:10] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:34:10] "GET /config_login HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:34:11] "GET /_dash-layout HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:34:11] "GET /_dash-dependencies HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:34:11] "POST /_dash-update-component HTTP/1.1" 200 -
172.30.32.1 - - [26/Nov/2021 15:34:11] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [26/Nov/2021 15:34:11] "POST /_dash-update-component HTTP/1.1" 204 -
172.30.32.1 - - [26/Nov/2021 15:34:11] "POST /_dash-update-component HTTP/1.1" 200 -
Requested API level 30 is larger than maximum we have, returning API level 28 instead.
/psa_car_controller/docker_files/init.sh: line 5:     9 Killed                  python3 -u /psa_car_controller/server.py $ARGS`

Home Assistant 2021.11.5
PSA v2.5.5

Thanks for help 👍

**Comment by azcn2503** [comment]
I get the same error running:

* Home Assistant Core v2021.11.5
* Supervisor v2021.10.8
* Add-on v2.5.6

**Comment by JulienADD** [comment]
Works fine with the last version ! Thanks !
