### ISSUE TITLE
Endpoint give no response

### ISSUE THREAD

**Issue by nagydavid** [flobz/psacc-ha#17]
Hi @flobz 

**Issue:** 
updated from 2.5.4 to 2.6.0
data available, in the UI(table, plotly, etc)
abrp connected, data there.
but http://192.168.50.188:5000/get_vehicleinfo/VR3UKZKXZLJ909961 endpoint fails to respond. 

setup:

HA addon
HA Version | core-2021.12.2
m Family | Linux
Operating System Version | 5.10.63-v8
CPU Architecture | aarch64

ps.: I checked issues, and FAQ, but saw nothing related, may be I overlooked.

**Comment by flobz** [comment]
Close as it doesn't follow the bug template
