### ISSUE TITLE
Error on Home Assistant

### ISSUE THREAD

**Issue by aferraz** [flobz/psacc-ha#2]
Hi,
 isntalled without problems on HA but got this error on login:
File is not a zip file

Thanks
 Alessandro

**Comment by lorddoener** [comment]
same for me: 

Car brand: Opel
Country code: DE




## System Health

version | core-2021.6.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4844
Installed Version | 1.13.2
Stage | running
Available Repositories | 849
Installed Repositories | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.6
docker_version | 20.10.6
disk_total | 58.0 GB
disk_used | 6.1 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Visual Studio Code (3.4.1), Terminal & SSH (9.1.3), SSH & Web Terminal (8.2.3), Spotify Connect (0.8.2), File editor (5.3.1), Home Assistant Google Drive Backup (0.104.3), PSA Car Controller (v2.4.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 14
views | 7
mode | storage

</details>

**Comment by aferraz** [comment]
Hi,
 i ran into the same problem with standard docker container.
I solved by replacing file mypeugeot.apk with the real APK.

Hope it can help

Regards
 Alessandro

**Comment by aferraz** [comment]
Solved with last changes
