### ISSUE TITLE
3.0.3 eternal “loading…”

### ISSUE THREAD

**Issue by albenex** [flobz/psacc-ha#20]
Hi,
i had a working 2.6.0 psacc addon installed inside my HA instance.
updated to 3.0.3 and it couldn’t boot with eternal “Loading…” screen.

then i tried rebooting either addon and HA with no change.

i eventually uninstalled and installed again (probably losing old data) and still no change.

below logs:
`Containerised psa_car_controller loading...
2022-05-01 22:31:33,652 :: ERROR :: Bad config
2022-05-01 22:31:33,662 :: WARNING :: Can't get language
2022-05-01 22:31:35,235 :: INFO :: update_data `

**Comment by DavidFFerreira** [comment]
Yup, updated yesterday and same thing

**Comment by DavidFFerreira** [comment]
I hope to not lose all data again =/

**Comment by flobz** [comment]
Please open an issue in the correct repository. I downgrade the version to 2.6.0 meanwhile.
