### ISSUE TITLE
sensor.yaml

### ISSUE THREAD

**Issue by phoenix-blue** [flobz/psacc-ha#29]
Hi,

I have installed the add-on module that's working fine.
But I don't get the sensor.yaml config working, i think it's the IP add. i have try my local HA IP addres, and also 127.0.0.1 and 0.0.0.0 but nothing works.
Port is default 5000/tcp and i use the "YourVIN" code from the car, so what do i wrong?
Thanks for helping.

**Comment by villegar** [comment]
Do you have the following line in your `/config/configuration.yaml` file? I was missing this line and I couldn't see the sensors:
```
sensor: !include sensor.yaml
```
