### ISSUE TITLE
where does the configuration live?

### ISSUE THREAD

**Issue by RMHogervorst** [flobz/psacc-ha#31]
When I install this in home assistant it works, but I'd like to modify the configuration. like adding keys for openweather/abrp etc. 

I can't find the settings like the cars.json and config that this should create.

**Comment by RMHogervorst** [comment]
I learned from the issues in the other repository that the config lives inside the docker container. 
Can we map the config folder to the home assistant config folder? I believe that is possible like here: https://developers.home-assistant.io/docs/add-ons/configuration#optional-configuration-options

**Comment by RMHogervorst** [comment]
Current HA config is written in yaml, so I guess something like this?

```
{
  "name": "PSA Car Controller",
  "version": "v3.0.11",
  "slug": "psacc",
  "description": "Control and get information from your PSA car",
  "arch": [
    "amd64",
    "armhf",
    "aarch64"
  ],
  "url": "https://github.com/flobz/psa_car_controller",
  "startup": "application",
  "boot": "auto",
  "ports_description": {"5000/tcp": "Web interface"},
  "ports": {
    "5000/tcp": null
    },
  "image": "flobz/psa_car_controller",
  "legacy": true,
  "ingress": true,
  "ingress_port": 5000,
  "panel_icon": "mdi:car",
  "environment": {"PSACC_PORT": "5000", "PSACC_CONFIG_DIR": "/data"},
  "options": { "PSACC_OPTIONS": "-r --web-conf -c" },
  "map": ["config:rw"],
  "schema": { "PSACC_OPTIONS": "str" }
}
```

**Comment by Voz-DeCarabas** [comment]
I agree with the feature request.  
In the interim for those that want a more hands on approach you could have a look at the discussion here https://github.com/flobz/psa_car_controller/discussions/249#discussioncomment-1862930 which allowed me to update the config for my HA on Pi.

Be careful, though.  Get it wrong and you will need to reinstall the add-on and will lose the data from past trips.

**Comment by flobz** [comment]
https://github.com/flobz/psacc-ha/tree/main/psacc-ha#modify-config-file
