### ISSUE TITLE
error when i stall addon

### ISSUE THREAD

**Issue by riddik14** [flobz/psacc-ha#34]
Can't install flobz/psa_car_controller:v3.0.12: 404 Client Error for http+docker://localhost/v1.42/images/flobz/psa_car_controller:v3.0.12/json: Not Found ("No such image: flobz/psa_car_controller:v3.0.12")

**Comment by solproget** [comment]
Me too with the same problem.
How can I fix?
![Screenshot 2023-07-11 124259](https://github.com/flobz/psacc-ha/assets/77103958/796a0546-eb35-4b77-be50-92758738fe73)
