### ISSUE TITLE
Find config file

### ISSUE THREAD

**Issue by Slin-nilS** [flobz/psacc-ha#35]
Hi, I´m searching for the config file. The path from the grep command (manual) din´t exist. 

System Information:
-Pi 4 SSD Boot
-Home Assistant 2023.10.3
-Supervisor 2023.10.0
-Operating System 11.0
-Frontend 20231005.0 - latest

```ssh
➜  ~ docker inspect -f '{{ .Mounts }}' $(docker ps -aqf "name=acc") | grep -o '/mnt/data[^ ]*psacc'
/mnt/data/supervisor/addons/data/b9f12d83_psacc
➜  ~ cd /mnt
➜  /mnt ls -lahtr
total 8K
drwxr-xr-x    2 root     root        4.0K Sep 28 13:23 .
drwxr-xr-x    1 root     root        4.0K Oct 18 15:16 ..
➜  /mnt

**Comment by Holewijn** [comment]
same here can't find it

**Comment by Slin-nilS** [comment]
@Holewijn After no further response, I moved it ([#639](https://github.com/flobz/psa_car_controller/issues/639) ), although I think this would have been the right place.

**Comment by Slin-nilS** [comment]
@Holewijn  Hi, look [there](https://github.com/flobz/psa_car_controller/issues/639) again. I found it. :-)
