### ISSUE TITLE
HA Addon

### ISSUE THREAD

**Issue by aferraz** [flobz/psacc-ha#4]
Hi,
how can i set the electricity proce on HA addon ?

Regards
 Alessandro

**Comment by Flodu31** [comment]
Yes, same for me. Can we add the price for electricity please?
Instead of editing the file, in the docker container.
Thanks.
Florent

**Comment by flobz** [comment]
You can have acces to the file in the host server. Edit it ! :)

**Comment by atze09** [comment]
> You can have acces to the file in the host server. Edit it ! :)

Where is it stored?
